name: 生成7种贡献SVG动画✨
on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 打印or创建目录
        run: |
          echo "当前目录文件：$(ls -lR)"
          mkdir -p assets
          mkdir -p dist

      - name: 生成 贪吃蛇SVG
        uses: platane/snk@v3
        with:
          github_user_name: Lin-arm
          outputs: assets/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置 Node.js 20 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 生成SVG (吃豆人 & 打砖块 & 太空战机 & 谜题泡泡 & 炸弹人 & 扫雷)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Lin-arm
          github_token: ${{ secrets.GITHUB_TOKEN }}
          games: 'pacman,breakout,galaga,puzzle-bobble,bomberman,minesweeper'

      - name: 将浅色/深色全套SVG移动并重命名到 assets
        run: |
          echo "当前目录文件：$(ls -lR)"
          for file in dist/*.svg; do
            # 取出纯文件名
            fn=$(basename "$file")
            # 以 "-" 分割，取第一段为游戏名
            game=$(echo "$fn" | cut -d'-' -f1)
            if [[ "$fn" == *"-dark.svg" ]]; then
              mv "$file" "assets/${game}-dark.svg"
            else
              mv "$file" "assets/${game}.svg"
            fi
          done

      - name: 提交所有SVG并推送到仓库
        run: |
          git config --global user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          git diff --staged --quiet || (git commit -m "chore: ✨生成7种稳定的贡献动画SVG" && git push)
